-- NM-4 (docs/060 §3.3, §3.4, §7.6): form-login attempts pulled from the auth-service login-event outbox.
-- Never edit this file after it is merged to main; add a new version instead.
-- Write mode: upsert, do nothing on event_id. Retention 180 d.
CREATE TABLE netmon.login_events (
    id             bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- Generated by auth-service; the idempotency key of every replayed page.
    event_id       uuid        NOT NULL,
    occurred_at    timestamptz NOT NULL,
    outcome        text        NOT NULL,
    -- CF-Connecting-IP, else the request's remote address; null when neither was a valid IP literal.
    client_ip      inet,
    ip_source      text        NOT NULL,
    -- Lowercase hex HMAC-SHA256 of lowercase(trim(submitted username)); the key stays in auth-service.
    username_hmac  char(64)    NOT NULL,
    -- Plaintext username, set only for success.
    subject        text,
    -- Truncated to 512 characters.
    user_agent     text,
    source_service text        NOT NULL,
    source         text        NOT NULL,
    ingested_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT login_events_event_id_key UNIQUE (event_id),
    CONSTRAINT login_events_outcome CHECK (outcome IN ('success', 'failure', 'locked')),
    CONSTRAINT login_events_ip_source CHECK (ip_source IN ('cf-connecting-ip', 'remote-addr')),
    CONSTRAINT login_events_username_hmac CHECK (username_hmac ~ '^[0-9a-f]{64}$'),
    CONSTRAINT login_events_subject CHECK (subject IS NULL OR outcome = 'success'),
    CONSTRAINT login_events_user_agent CHECK (user_agent IS NULL OR char_length(user_agent) <= 512)
);
CREATE INDEX login_events_occurred_at_idx ON netmon.login_events (occurred_at);
CREATE INDEX login_events_client_ip_idx ON netmon.login_events (client_ip, occurred_at);
CREATE INDEX login_events_username_hmac_idx ON netmon.login_events (username_hmac, occurred_at);
